delete_previous_images: true
delete_previous_items: 30
extensions:
- jpg
- jpeg
- png
- gif
- psd
resources: /Users/claude/whelper/resources/
save_directory: /Users/claude/Desktop/wconcept
version: 0.9.0
