delete_previous_images: true
delete_previous_items: 30
extensions:
- jpg
- jpeg
- png
- gif
- psd
resources: /Users/minah/whelper/resources/
save_directory: /Users/minah/Desktop/wconcept
version: 0.8.0
